version: '3.8'

services:
  db:
    image: postgres
    container_name: wallet-service-db
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: always
    ports:
      - "5435:5432"